#!/usr/bin/env php
<?php

chdir(getenv('APPLICATION_PATH')?:__DIR__);

if (!is_readable('config.ini'))
	die('Run from application directory or define APPLICATION_PATH'."\n");

$_SERVER['SCRIPT_FILENAME'] = getcwd() .'/htdocs/index.php';

require('htdocs/index.php');